export class TileService{
  tiles = [
    [
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      }
    ],
    [
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      }
    ],
    [
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      }
    ],
    [
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      }
    ],
    [
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      }
    ],
    [
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      }
    ],
    [
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      },
      {
        color:'board__tile--white'
      }
    ]
  ];

  //The function to drop a coin in the board
  coinDrop(col:number, player:number){
    //Default tile color
    let playerColorClass = 'board__tile--white';
    //Set the player color to the tile
    if(player==1){
      playerColorClass='board__tile--blue';
    }
    else if(player==2){
      playerColorClass='board__tile--red';
    }

    //Search for the tile to set the color
    let found = false;
    for (let tile of this.tiles[col].reverse()) {
      if(!found && tile.color=='board__tile--white'){
          tile.color=playerColorClass;
          found=true;
      }
    }
    this.tiles[col].reverse()
  }

}
